---
title: "Lecture 02"
format: html
editor: visual
---

## Slides

```{r}
pacman::p_load(ape, animint,bayesplot, brms, broom, dagitty, devtools, flextable, GGally, ggdag, ggdark, ggmcmc, ggrepel, ggthemes, ggtree, ghibli, gtools, invgamma, loo, patchwork, posterior, psych, rcartocolor, Rcpp, remotes, rethinking, rstan, santoku, StanHeaders, statebins, tidybayes, tidyverse, viridis, viridisLite, wesanderson)

```

Steps:

1.  Define generative model of the sample

    -   We have 4 variables:

        -   p: proportion of water (estimand)
        -   N: number of tosses
        -   W: water observations
        -   L: land observations

    -   Influences:

        -   N-\>W ; N-\>L; p-\>W; p-\>L

        -   W,L = f(p,N)

2.  Define a specific estimand

    -   p

3.  Design a statistical way to produce estimand

    -   W,L = (4p)^W^ + (4-4p)^L^

        ```{r}
        sample <- c("W","L","W","W","W","L","W","L","W")
        W <- sum(sample=="W")
        L <- sum(sample=="L")
        p <- c(0,0.25,0.5,0.75,1)
        ways <- sapply(p, function(q) (q*4)^W*((4-4*q)^L))
        prob <- ways/sum(ways)
        cbind(p, ways, prob)
        ```

4.  Test 3 using 1

    ```{r}
    # function to toss a globe covered in water N times
    sim_globe <- function(p=0.7, N=9){
      sample(c("W","L"), size=N, prob=c(p,1-p), replace = T)
    }
    print(sim_globe())
    #test 1: Extreme tests, result should be obvious
    print(sim_globe(p=1,N=11))
    #test 2: large cases, result should be =p
    print(sum(sim_globe(p=0.5, N=1e4)=="W")/1e4)
    ```

5.  Analyze sample, summarize

```{r}
compute_posterior <- function(the_sample, poss=c(0,0.25,0.5,0.75,1)){
  sample <- c("W","L","W","W","W","L","W","L","W")
W <- sum(sample=="W")
L <- sum(sample=="L")
ways <- sapply(poss, function(q) (q*4)^W*((4-4*q)^L))
post <- ways/sum(ways)
#bars <- sapply(post, function(q) make_bar(q))
data.frame(poss, ways, post=round(post,3))

}
compute_posterior(sim_globe())
```

Sampling the posterior

```{r}
post_samples <- rbeta(1e3, 6+1, 3+1)
dens(post_samples, lwd=4, col=2, xlab="proportion water", adj=0.1)
curve(dbeta(x, 6+1, 3+1), add=T, lty=2, lwd=3)
```

## Code

(https://bookdown.org/content/4857/the-golem-of-prague.html)

```{r}
library(tidyverse)

```

```{r}
sessionInfo()
```
